---
name: ansible-lint
on: [push, pull_request]

jobs:

  ansible-lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
        with:
          path: "roles/"
